### PR TITLE
Update arc42 images

### PR DESCRIPTION
**Pull request by jkroepke**
See #44

### CODE REVIEW

**Comment by jkroepke** [comment]
@DG0lden 
It's possible to test your this image?

With this PR, i'll adding monthly snapshots of this image like here: https://hub.docker.com/r/adorsys/ci-build/tags

**Comment by DG0lden** [comment]
With `make` and `rsync` it generates everything correctly!

**Comment by DG0lden** [comment]
added PR for it: https://github.com/adorsys/dockerhub-pipeline-images/pull/49 to this branch

**Comment by DG0lden** [comment]
@jkroepke Why closed? You didn't merged anything to master

**Comment by jkroepke** [comment]
I didn't see that #49 merged into this.

**Pull request merged**
